import { describe, it } from "node:test";
import assert from "node:assert/strict";
import type { ScanResult, DetectedService } from "../scanner/types.js";
import { generateDataLifecycleDiagram } from "./data-lifecycle-diagram.js";
import type { GeneratorContext } from "./index.js";

function makeService(
  name: string,
  category: DetectedService["category"],
  dataCollected: string[] = ["test data"],
): DetectedService {
  return {
    name,
    category,
    evidence: [{ type: "dependency", file: "package.json", detail: `${name} detected` }],
    dataCollected,
  };
}

function makeScan(overrides: Partial<ScanResult> = {}): ScanResult {
  return {
    projectName: "test-project",
    projectPath: "/tmp/test",
    scannedAt: "2026-01-01",
    services: [],
    dataCategories: [],
    complianceNeeds: [],
    ...overrides,
  };
}

describe("generateDataLifecycleDiagram", () => {
  // ── Null return cases ──────────────────────────────────────────────

  it("returns null when services array is empty", () => {
    const scan = makeScan({ services: [] });
    assert.strictEqual(generateDataLifecycleDiagram(scan), null);
  });

  it("returns null when services have unsupported categories only", () => {
    const scan = makeScan({
      services: [makeService("cdn-provider", "cdn" as DetectedService["category"])],
    });
    // cdn is not mapped in inferDataTypes, so dataTypes will be empty
    const result = generateDataLifecycleDiagram(scan);
    assert.strictEqual(result, null);
  });

  // ── Basic output ──────────────────────────────────────────────────

  it("generates output when auth service present", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan);
    assert.ok(result !== null);
    assert.ok(typeof result === "string");
  });

  it("includes title with company name", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const ctx: GeneratorContext = { companyName: "Acme Corp", contactEmail: "a@acme.com" };
    const result = generateDataLifecycleDiagram(scan, ctx)!;
    assert.ok(result.includes("# Data Lifecycle Diagram — Acme Corp"));
  });

  it("uses placeholder company name when no context", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("[Your Company Name]"));
  });

  it("includes date in YYYY-MM-DD format", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(/\d{4}-\d{2}-\d{2}/.test(result));
  });

  it("includes auto-generated attribution", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("Auto-generated by Codepliant"));
  });

  // ── Lifecycle Overview ────────────────────────────────────────────

  it("includes lifecycle overview section", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("## Lifecycle Overview"));
    assert.ok(result.includes("**Collection**"));
    assert.ok(result.includes("**Processing**"));
    assert.ok(result.includes("**Storage**"));
    assert.ok(result.includes("**Sharing**"));
    assert.ok(result.includes("**Deletion**"));
  });

  // ── Mermaid diagram ───────────────────────────────────────────────

  it("includes mermaid diagram", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("```mermaid"));
    assert.ok(result.includes("graph LR"));
  });

  it("mermaid diagram has lifecycle subgraph", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("subgraph Lifecycle"));
  });

  it("mermaid diagram has per-data-type subgraphs", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("stripe", "payment"),
      ],
    });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("subgraph DT0"));
    assert.ok(result.includes("subgraph DT1"));
  });

  // ── Auth data type ────────────────────────────────────────────────

  it("infers Identity & Account Data for auth services", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("Identity & Account Data"));
  });

  it("shows auth service name as source", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("next-auth"));
  });

  it("shows auth retention period", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("Until account deletion"));
  });

  // ── Payment data type ─────────────────────────────────────────────

  it("infers Payment & Billing Data for payment services", () => {
    const scan = makeScan({ services: [makeService("stripe", "payment")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("Payment & Billing Data"));
  });

  it("shows payment retention period of 7 years", () => {
    const scan = makeScan({ services: [makeService("stripe", "payment")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("7 years (tax/legal)"));
  });

  // ── Analytics data type ───────────────────────────────────────────

  it("infers Behavioral & Analytics Data for analytics services", () => {
    const scan = makeScan({ services: [makeService("ga", "analytics")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("Behavioral & Analytics Data"));
  });

  it("shows analytics retention period of 26 months", () => {
    const scan = makeScan({ services: [makeService("ga", "analytics")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("26 months"));
  });

  // ── AI data type ──────────────────────────────────────────────────

  it("infers AI Interaction Data for AI services", () => {
    const scan = makeScan({ services: [makeService("openai", "ai")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("AI Interaction Data"));
  });

  it("shows AI retention period of 90 days", () => {
    const scan = makeScan({ services: [makeService("openai", "ai")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("90 days"));
  });

  // ── Email data type ───────────────────────────────────────────────

  it("infers Communication Data for email services", () => {
    const scan = makeScan({ services: [makeService("sendgrid", "email")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("Communication Data"));
  });

  it("shows email retention period of 3 years", () => {
    const scan = makeScan({ services: [makeService("sendgrid", "email")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("3 years"));
  });

  // ── Monitoring data type ──────────────────────────────────────────

  it("infers Technical & Error Data for monitoring services", () => {
    const scan = makeScan({ services: [makeService("sentry", "monitoring")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("Technical & Error Data"));
  });

  // ── Database/Storage data type ────────────────────────────────────

  it("infers User-Generated Content for database services", () => {
    const scan = makeScan({ services: [makeService("prisma", "database")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("User-Generated Content"));
  });

  it("infers User-Generated Content for storage services", () => {
    const scan = makeScan({ services: [makeService("s3", "storage")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("User-Generated Content"));
  });

  // ── Retention Summary table ───────────────────────────────────────

  it("includes retention summary table", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("## Retention Summary"));
    assert.ok(result.includes("| Data Type | Retention Period | Deletion Trigger |"));
  });

  // ── Detailed Lifecycle per Data Type ──────────────────────────────

  it("includes detailed lifecycle section", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("## Detailed Lifecycle per Data Type"));
  });

  it("includes lifecycle stages table for each data type", () => {
    const scan = makeScan({ services: [makeService("stripe", "payment")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("| Collection |"));
    assert.ok(result.includes("| Processing |"));
    assert.ok(result.includes("| Storage |"));
    assert.ok(result.includes("| Sharing |"));
    assert.ok(result.includes("| Retention |"));
    assert.ok(result.includes("| Deletion |"));
  });

  // ── Lifecycle Stage Details ───────────────────────────────────────

  it("includes lifecycle stage details sections", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("## Lifecycle Stage Details"));
    assert.ok(result.includes("### Collection"));
    assert.ok(result.includes("### Processing"));
    assert.ok(result.includes("### Storage"));
    assert.ok(result.includes("### Sharing"));
    assert.ok(result.includes("### Deletion"));
  });

  // ── Multiple data types ───────────────────────────────────────────

  it("includes multiple data types when multiple categories present", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("stripe", "payment"),
        makeService("openai", "ai"),
      ],
    });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("Identity & Account Data"));
    assert.ok(result.includes("Payment & Billing Data"));
    assert.ok(result.includes("AI Interaction Data"));
  });

  it("does not duplicate data types when multiple services of same category", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("clerk", "auth"),
      ],
    });
    const result = generateDataLifecycleDiagram(scan)!;
    // Count occurrences of "### Identity & Account Data"
    const matches = result.match(/### Identity & Account Data/g);
    assert.strictEqual(matches?.length, 1);
  });

  it("lists multiple auth services as sources", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("clerk", "auth"),
      ],
    });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("next-auth"));
    assert.ok(result.includes("clerk"));
  });

  // ── Disclaimer ────────────────────────────────────────────────────

  it("includes disclaimer", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("automated code analysis"));
    assert.ok(result.includes("does not constitute legal advice"));
  });

  // ── Full scenario ─────────────────────────────────────────────────

  it("generates all seven data types when all categories present", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("stripe", "payment"),
        makeService("ga", "analytics"),
        makeService("openai", "ai"),
        makeService("sendgrid", "email"),
        makeService("sentry", "monitoring"),
        makeService("prisma", "database"),
      ],
    });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("Identity & Account Data"));
    assert.ok(result.includes("Payment & Billing Data"));
    assert.ok(result.includes("Behavioral & Analytics Data"));
    assert.ok(result.includes("AI Interaction Data"));
    assert.ok(result.includes("Communication Data"));
    assert.ok(result.includes("Technical & Error Data"));
    assert.ok(result.includes("User-Generated Content"));
  });

  it("mermaid diagram styling matches number of data types", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("stripe", "payment"),
        makeService("openai", "ai"),
      ],
    });
    const result = generateDataLifecycleDiagram(scan)!;
    assert.ok(result.includes("style DT0"));
    assert.ok(result.includes("style DT1"));
    assert.ok(result.includes("style DT2"));
    assert.ok(!result.includes("style DT3"));
  });
});
