import { describe, it } from "node:test";
import assert from "node:assert/strict";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { generateEnvExample, writeEnvExample } from "./env-example.js";
import type { ScanResult, DetectedService } from "../scanner/index.js";

// --- Test helpers ---

function makeService(
  name: string,
  category: DetectedService["category"],
  dataCollected: string[] = ["test data"],
  isDataProcessor?: boolean
): DetectedService {
  return {
    name,
    category,
    evidence: [{ type: "dependency", file: "package.json", detail: `${name} detected` }],
    dataCollected,
    ...(isDataProcessor !== undefined ? { isDataProcessor } : {}),
  };
}

function makeScan(services: DetectedService[] = []): ScanResult {
  return {
    projectName: "test-project",
    projectPath: "/tmp/test",
    scannedAt: "2026-01-01",
    services,
    dataCategories: [],
    complianceNeeds: [],
  };
}

describe("generateEnvExample", () => {
  it("returns empty string for empty scan", () => {
    const result = generateEnvExample(makeScan());
    assert.strictEqual(result, "");
  });

  it("returns empty string when no services have env patterns", () => {
    const scan = makeScan([
      makeService("@vercel/analytics", "analytics"),
      makeService("passport", "auth"),
    ]);
    const result = generateEnvExample(scan);
    assert.strictEqual(result, "");
  });

  it("generates env vars for OpenAI", () => {
    const scan = makeScan([makeService("openai", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("OPENAI_API_KEY=sk-your-key-here"));
    assert.ok(result.includes("# === AI Services ==="));
  });

  it("generates env vars for Stripe", () => {
    const scan = makeScan([makeService("stripe", "payment")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("STRIPE_SECRET_KEY=rk_test_REPLACE_ME"));
    assert.ok(result.includes("STRIPE_PUBLISHABLE_KEY=pk_test_your-key"));
    assert.ok(result.includes("STRIPE_WEBHOOK_SECRET=whsec_your-secret"));
    assert.ok(result.includes("# === Payment ==="));
  });

  it("generates env vars for Sentry", () => {
    const scan = makeScan([makeService("@sentry/node", "monitoring")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("SENTRY_DSN=https://"));
    assert.ok(result.includes("# === Monitoring ==="));
  });

  it("generates env vars for NextAuth", () => {
    const scan = makeScan([makeService("next-auth", "auth")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("NEXTAUTH_SECRET=your-secret-here"));
    assert.ok(result.includes("NEXTAUTH_URL=http://localhost:3000"));
    assert.ok(result.includes("# === Authentication ==="));
  });

  it("groups vars by category with section headers", () => {
    const scan = makeScan([
      makeService("openai", "ai"),
      makeService("stripe", "payment"),
      makeService("next-auth", "auth"),
    ]);
    const result = generateEnvExample(scan);

    const aiIdx = result.indexOf("# === AI Services ===");
    const paymentIdx = result.indexOf("# === Payment ===");
    const authIdx = result.indexOf("# === Authentication ===");

    assert.ok(aiIdx >= 0, "AI section header should exist");
    assert.ok(paymentIdx >= 0, "Payment section header should exist");
    assert.ok(authIdx >= 0, "Auth section header should exist");

    // AI comes before Payment, Payment before Auth (per CATEGORY_ORDER)
    assert.ok(aiIdx < paymentIdx, "AI should come before Payment");
    assert.ok(paymentIdx < authIdx, "Payment should come before Auth");
  });

  it("includes file header with instructions", () => {
    const scan = makeScan([makeService("openai", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("Generated by Codepliant"));
    assert.ok(result.includes("Copy this file to .env.local"));
    assert.ok(result.includes("NEVER commit .env.local"));
  });

  it("deduplicates env vars across services", () => {
    // Both sentry/node and sentry/nextjs use SENTRY_DSN
    const scan = makeScan([
      makeService("@sentry/node", "monitoring"),
      makeService("@sentry/nextjs", "monitoring"),
    ]);
    const result = generateEnvExample(scan);

    const matches = result.match(/^SENTRY_DSN=/gm);
    assert.strictEqual(matches?.length, 1, "SENTRY_DSN should appear exactly once");
  });

  it("excludes non-data-processor services", () => {
    const scan = makeScan([
      makeService("zod", "other", ["validated user input"], false),
      makeService("openai", "ai"),
    ]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("OPENAI_API_KEY"));
    // zod has no env patterns anyway, but ensure it's filtered
    assert.ok(!result.includes("zod"));
  });

  it("generates database env vars", () => {
    const scan = makeScan([makeService("prisma", "database")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("PRISMA_DATABASE_URL="));
    assert.ok(result.includes("# === Database ==="));
  });

  it("generates email service env vars", () => {
    const scan = makeScan([makeService("@sendgrid/mail", "email")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("SENDGRID_API_KEY="));
    assert.ok(result.includes("# === Email ==="));
  });

  it("generates storage env vars", () => {
    const scan = makeScan([makeService("@aws-sdk/client-s3", "storage")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("AWS_ACCESS_KEY_ID="));
    assert.ok(result.includes("AWS_SECRET_ACCESS_KEY="));
    assert.ok(result.includes("# === Storage ==="));
  });

  it("handles multiple services in same category", () => {
    const scan = makeScan([
      makeService("openai", "ai"),
      makeService("@anthropic-ai/sdk", "ai"),
    ]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("OPENAI_API_KEY="));
    assert.ok(result.includes("ANTHROPIC_API_KEY="));

    // Only one AI header
    const headers = result.match(/# === AI Services ===/g);
    assert.strictEqual(headers?.length, 1);
  });

  // ── New tests: additional service coverage ──────────────────────────

  it("generates env vars for Anthropic SDK", () => {
    const scan = makeScan([makeService("@anthropic-ai/sdk", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("ANTHROPIC_API_KEY=sk-ant-your-key-here"));
    assert.ok(result.includes("CLAUDE_API_KEY=sk-ant-your-key-here"));
  });

  it("generates env vars for Google AI", () => {
    const scan = makeScan([makeService("@google/generative-ai", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("GOOGLE_AI_KEY="));
    assert.ok(result.includes("GEMINI_API_KEY="));
  });

  it("generates env vars for Replicate", () => {
    const scan = makeScan([makeService("replicate", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("REPLICATE_API_TOKEN=r8_your-token-here"));
  });

  it("generates env vars for Cohere", () => {
    const scan = makeScan([makeService("cohere", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("COHERE_API_KEY="));
    assert.ok(result.includes("CO_API_KEY="));
  });

  it("generates env vars for Pinecone", () => {
    const scan = makeScan([makeService("@pinecone-database/pinecone", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("PINECONE_API_KEY=your-pinecone-api-key"));
    assert.ok(result.includes("PINECONE_ENVIRONMENT=us-east-1-aws"));
  });

  it("generates env vars for PayPal", () => {
    const scan = makeScan([makeService("@paypal/checkout-server-sdk", "payment")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("PAYPAL_CLIENT_ID="));
    assert.ok(result.includes("PAYPAL_CLIENT_SECRET="));
  });

  it("generates env vars for Supabase", () => {
    const scan = makeScan([makeService("@supabase/supabase-js", "auth")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("SUPABASE_URL=https://your-project.supabase.co"));
    assert.ok(result.includes("SUPABASE_ANON_KEY="));
    assert.ok(result.includes("SUPABASE_SERVICE_ROLE="));
  });

  it("generates env vars for PostHog", () => {
    const scan = makeScan([makeService("posthog", "analytics")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("POSTHOG_API_KEY=phc_your-posthog-key"));
    assert.ok(result.includes("# === Analytics ==="));
  });

  it("generates env vars for Resend email", () => {
    const scan = makeScan([makeService("resend", "email")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("RESEND_API_KEY=re_your-resend-api-key"));
  });

  it("generates env vars for Drizzle database", () => {
    const scan = makeScan([makeService("drizzle", "database")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("DRIZZLE_DATABASE_URL=postgresql://"));
  });

  it("generates env vars for MongoDB", () => {
    const scan = makeScan([makeService("mongoose", "database")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("MONGODB_URI=mongodb://"));
  });

  it("generates env vars for Clerk auth", () => {
    const scan = makeScan([makeService("@clerk/nextjs", "auth")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("CLERK_SECRET_KEY="));
    assert.ok(result.includes("CLERK_PUBLISHABLE_KEY="));
  });

  // ── Category ordering tests ─────────────────────────────────────────

  it("orders database before email category", () => {
    const scan = makeScan([
      makeService("@sendgrid/mail", "email"),
      makeService("prisma", "database"),
    ]);
    const result = generateEnvExample(scan);
    const dbIdx = result.indexOf("# === Database ===");
    const emailIdx = result.indexOf("# === Email ===");
    assert.ok(dbIdx < emailIdx, "Database should come before Email");
  });

  it("orders auth before database category", () => {
    const scan = makeScan([
      makeService("prisma", "database"),
      makeService("next-auth", "auth"),
    ]);
    const result = generateEnvExample(scan);
    const authIdx = result.indexOf("# === Authentication ===");
    const dbIdx = result.indexOf("# === Database ===");
    assert.ok(authIdx < dbIdx, "Auth should come before Database");
  });

  it("orders analytics before monitoring category", () => {
    const scan = makeScan([
      makeService("@sentry/node", "monitoring"),
      makeService("posthog", "analytics"),
    ]);
    const result = generateEnvExample(scan);
    const analyticsIdx = result.indexOf("# === Analytics ===");
    const monitoringIdx = result.indexOf("# === Monitoring ===");
    assert.ok(analyticsIdx < monitoringIdx, "Analytics should come before Monitoring");
  });

  // ── Output format tests ─────────────────────────────────────────────

  it("includes date in the header", () => {
    const scan = makeScan([makeService("openai", "ai")]);
    const result = generateEnvExample(scan);
    // Header should contain a date in YYYY-MM-DD format
    assert.ok(/# \d{4}-\d{2}-\d{2}/.test(result), "Header should include date");
  });

  it("ends with a trailing newline", () => {
    const scan = makeScan([makeService("openai", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.endsWith("\n"), "Output should end with newline");
  });

  it("uses KEY=value format for all env vars", () => {
    const scan = makeScan([
      makeService("openai", "ai"),
      makeService("stripe", "payment"),
    ]);
    const result = generateEnvExample(scan);
    const lines = result.split("\n").filter(l => !l.startsWith("#") && l.trim() !== "");
    for (const line of lines) {
      assert.ok(/^[A-Z_]+=.+$/.test(line), `Line should be KEY=value format: ${line}`);
    }
  });

  it("does not include blank lines between vars in the same category", () => {
    const scan = makeScan([makeService("stripe", "payment")]);
    const result = generateEnvExample(scan);
    // Find the payment section
    const paymentStart = result.indexOf("# === Payment ===");
    const afterPayment = result.substring(paymentStart);
    const lines = afterPayment.split("\n");
    // After the header, vars should be consecutive (no blank lines until next section)
    let foundFirstVar = false;
    for (let i = 1; i < lines.length; i++) {
      const line = lines[i];
      if (!foundFirstVar && /^[A-Z_]+=/.test(line)) {
        foundFirstVar = true;
        continue;
      }
      if (foundFirstVar) {
        if (line.trim() === "") break; // blank line means section ended
        assert.ok(/^[A-Z_]+=/.test(line), "Vars in same category should be consecutive");
      }
    }
  });

  // ── Full integration: all categories at once ────────────────────────

  it("handles all major categories simultaneously", () => {
    const scan = makeScan([
      makeService("openai", "ai"),
      makeService("stripe", "payment"),
      makeService("next-auth", "auth"),
      makeService("prisma", "database"),
      makeService("@aws-sdk/client-s3", "storage"),
      makeService("@sendgrid/mail", "email"),
      makeService("posthog", "analytics"),
      makeService("@sentry/node", "monitoring"),
    ]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("# === AI Services ==="));
    assert.ok(result.includes("# === Payment ==="));
    assert.ok(result.includes("# === Authentication ==="));
    assert.ok(result.includes("# === Database ==="));
    assert.ok(result.includes("# === Storage ==="));
    assert.ok(result.includes("# === Email ==="));
    assert.ok(result.includes("# === Analytics ==="));
    assert.ok(result.includes("# === Monitoring ==="));
  });

  it("returns string type always (not null or undefined)", () => {
    const result = generateEnvExample(makeScan());
    assert.strictEqual(typeof result, "string");
  });

  it("filters out service with isDataProcessor=false even if it has env patterns", () => {
    const scan = makeScan([
      makeService("openai", "ai", ["user prompts"], false),
    ]);
    const result = generateEnvExample(scan);
    assert.strictEqual(result, "");
  });

  it("includes service with isDataProcessor=true", () => {
    const scan = makeScan([
      makeService("openai", "ai", ["user prompts"], true),
    ]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("OPENAI_API_KEY="));
  });

  it("includes service with isDataProcessor=undefined (default)", () => {
    const scan = makeScan([
      makeService("openai", "ai", ["user prompts"]),
    ]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("OPENAI_API_KEY="));
  });
});

describe("writeEnvExample", () => {
  it("writes .env.example file to disk", () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "codepliant-test-"));
    try {
      const scan = makeScan([makeService("openai", "ai")]);
      const result = writeEnvExample(scan, tmpDir);

      assert.ok(result !== null);
      assert.ok(result!.endsWith(".env.example"));
      assert.ok(fs.existsSync(result!));

      const content = fs.readFileSync(result!, "utf-8");
      assert.ok(content.includes("OPENAI_API_KEY="));
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it("returns null when no services detected", () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "codepliant-test-"));
    try {
      const result = writeEnvExample(makeScan(), tmpDir);
      assert.strictEqual(result, null);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it("creates output directory if it does not exist", () => {
    const tmpDir = path.join(os.tmpdir(), `codepliant-test-${Date.now()}`);
    try {
      const scan = makeScan([makeService("stripe", "payment")]);
      const result = writeEnvExample(scan, tmpDir);

      assert.ok(result !== null);
      assert.ok(fs.existsSync(tmpDir));
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it("writes correct content matching generateEnvExample output", () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "codepliant-test-"));
    try {
      const scan = makeScan([makeService("openai", "ai"), makeService("stripe", "payment")]);
      const expected = generateEnvExample(scan);
      const filePath = writeEnvExample(scan, tmpDir);
      assert.ok(filePath !== null);
      const written = fs.readFileSync(filePath!, "utf-8");
      assert.strictEqual(written, expected);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it("overwrites existing .env.example file", () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "codepliant-test-"));
    try {
      fs.writeFileSync(path.join(tmpDir, ".env.example"), "OLD_CONTENT=old", "utf-8");
      const scan = makeScan([makeService("openai", "ai")]);
      const filePath = writeEnvExample(scan, tmpDir);
      assert.ok(filePath !== null);
      const content = fs.readFileSync(filePath!, "utf-8");
      assert.ok(!content.includes("OLD_CONTENT"));
      assert.ok(content.includes("OPENAI_API_KEY="));
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it("returns null for services without env patterns", () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "codepliant-test-"));
    try {
      const scan = makeScan([makeService("@vercel/analytics", "analytics")]);
      const result = writeEnvExample(scan, tmpDir);
      assert.strictEqual(result, null);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it("does not write file when result would be empty", () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "codepliant-test-"));
    try {
      writeEnvExample(makeScan(), tmpDir);
      assert.ok(!fs.existsSync(path.join(tmpDir, ".env.example")));
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it("creates nested output directories", () => {
    const tmpDir = path.join(os.tmpdir(), `codepliant-test-${Date.now()}`, "deep", "nested");
    try {
      const scan = makeScan([makeService("openai", "ai")]);
      const result = writeEnvExample(scan, tmpDir);
      assert.ok(result !== null);
      assert.ok(fs.existsSync(tmpDir));
      assert.ok(fs.existsSync(result!));
    } finally {
      fs.rmSync(path.join(os.tmpdir(), `codepliant-test-${Date.now()}`), { recursive: true, force: true });
      // Cleanup the actual created dir
      const base = tmpDir.split("/deep/")[0];
      if (fs.existsSync(base)) fs.rmSync(base, { recursive: true, force: true });
    }
  });
});
