import { describe, it } from "node:test";
import assert from "node:assert/strict";
import type { ScanResult, DetectedService } from "../scanner/types.js";
import { generateKeyPersonRiskAssessment } from "./key-person-risk.js";

function makeService(
  name: string,
  category: DetectedService["category"],
  dataCollected: string[] = ["test data"],
): DetectedService {
  return {
    name,
    category,
    evidence: [{ type: "dependency", file: "package.json", detail: `${name} detected` }],
    dataCollected,
  };
}

function makeScan(overrides: Partial<ScanResult> = {}): ScanResult {
  return {
    projectName: "test-project",
    projectPath: "/tmp/test",
    scannedAt: "2026-01-01",
    services: [],
    dataCategories: [],
    complianceNeeds: [],
    ...overrides,
  };
}

describe("generateKeyPersonRiskAssessment", () => {
  // ── Null returns ────────────────────────────────────────────────────────
  it("returns null when no services detected", () => {
    const result = generateKeyPersonRiskAssessment(makeScan());
    assert.strictEqual(result, null);
  });

  it("returns null for empty services array", () => {
    const result = generateKeyPersonRiskAssessment(makeScan({ services: [] }));
    assert.strictEqual(result, null);
  });

  // ── Basic generation ────────────────────────────────────────────────────
  it("generates document with services", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan);
    assert.ok(result !== null);
    assert.ok(result.includes("# Key Person Risk Assessment"));
  });

  it("includes current date", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    const today = new Date().toISOString().split("T")[0];
    assert.ok(result.includes(`Auto-generated by Codepliant on ${today}`));
  });

  it("includes Codepliant attribution", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Codepliant"));
  });

  // ── Context values ──────────────────────────────────────────────────────
  it("uses default placeholder when no context", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("[Your Company Name]"));
  });

  it("uses context company name", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan, {
      companyName: "Acme Corp",
      contactEmail: "contact@acme.com",
    })!;
    assert.ok(result.includes("Key Person Risk Assessment — Acme Corp"));
  });

  // ── Executive Summary ───────────────────────────────────────────────────
  it("includes Executive Summary with metrics", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("## Executive Summary"));
    assert.ok(result.includes("Key Compliance Roles"));
    assert.ok(result.includes("Critical Roles"));
    assert.ok(result.includes("Unassigned / Needs Assignment"));
    assert.ok(result.includes("Single Points of Failure"));
  });

  it("shows action required when roles are unassigned", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("**Action Required:**"));
    assert.ok(result.includes("role(s) need immediate assignment"));
  });

  // ── Core roles always present ───────────────────────────────────────────
  it("always includes DPO role", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Data Protection Officer (DPO)"));
    assert.ok(result.includes("DSAR handling"));
    assert.ok(result.includes("GDPR Art. 37-39"));
  });

  it("always includes Security Lead role", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Security Lead / CISO"));
    assert.ok(result.includes("vulnerability management"));
  });

  it("always includes Incident Response Lead role", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Incident Response Lead"));
    assert.ok(result.includes("data breaches"));
    assert.ok(result.includes("containment"));
  });

  it("always includes Compliance Training Coordinator role", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Compliance Training Coordinator"));
    assert.ok(result.includes("training records"));
  });

  // ── DPO assignment status ───────────────────────────────────────────────
  it("shows DPO as not assigned when no dpoName/dpoEmail", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("**Not assigned** — compliance risk"));
  });

  it("shows DPO as assigned when dpoName provided", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan, {
      companyName: "Acme",
      contactEmail: "contact@acme.com",
      dpoName: "Jane Smith",
      dpoEmail: "dpo@acme.com",
    })!;
    assert.ok(result.includes("Jane Smith"));
    assert.ok(result.includes("dpo@acme.com"));
    assert.ok(!result.includes("**Not assigned** — compliance risk"));
  });

  // ── Security Lead assignment ────────────────────────────────────────────
  it("shows security lead contact when securityEmail provided", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan, {
      companyName: "Acme",
      contactEmail: "contact@acme.com",
      securityEmail: "security@acme.com",
    })!;
    assert.ok(result.includes("Contact: security@acme.com"));
  });

  it("shows security lead as not formally assigned without securityEmail", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("[Not formally assigned]"));
  });

  // ── Conditional: Privacy Champion (analytics/advertising) ───────────────
  it("includes Privacy Champion when analytics detected", () => {
    const scan = makeScan({ services: [makeService("posthog", "analytics")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Privacy Champion / Consent Manager"));
    assert.ok(result.includes("consent management platform"));
    assert.ok(result.includes("ePrivacy Directive"));
  });

  it("includes Privacy Champion when advertising detected", () => {
    const scan = makeScan({ services: [makeService("meta-pixel", "advertising")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Privacy Champion / Consent Manager"));
  });

  it("omits Privacy Champion without analytics or advertising", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(!result.includes("Privacy Champion / Consent Manager"));
  });

  // ── Conditional: AI Governance Lead (ai) ────────────────────────────────
  it("includes AI Governance Lead when AI detected", () => {
    const scan = makeScan({ services: [makeService("openai", "ai")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("AI Governance Lead"));
    assert.ok(result.includes("EU AI Act"));
    assert.ok(result.includes("Art. 50"));
    assert.ok(result.includes("Colorado AI Act"));
  });

  it("omits AI Governance Lead without AI", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(!result.includes("AI Governance Lead"));
  });

  // ── Conditional: Vendor Management Lead (>= 3 services) ────────────────
  it("includes Vendor Management Lead with 3+ services", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("stripe", "payment"),
        makeService("posthog", "analytics"),
      ],
    });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Vendor Management Lead"));
    assert.ok(result.includes("3 detected third-party services"));
    assert.ok(result.includes("GDPR Art. 28"));
  });

  it("omits Vendor Management Lead with fewer than 3 services", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("stripe", "payment"),
      ],
    });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(!result.includes("Vendor Management Lead"));
  });

  it("shows correct service count in Vendor Management description", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("stripe", "payment"),
        makeService("posthog", "analytics"),
        makeService("openai", "ai"),
        makeService("sendgrid", "email"),
      ],
    });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("5 detected third-party services"));
  });

  // ── Key Person Risk Matrix ──────────────────────────────────────────────
  it("includes Risk Matrix table with headers", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("## Key Person Risk Matrix"));
    assert.ok(result.includes("| Role | Risk Level | SPOF | Assigned | Backup |"));
  });

  it("marks DPO as Critical risk level", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Critical"));
  });

  it("marks Compliance Training Coordinator as Medium risk level", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Medium"));
  });

  // ── Role Details section ────────────────────────────────────────────────
  it("includes Role Details section with cross-training recommendations", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("## Role Details"));
    assert.ok(result.includes("**Cross-Training Recommendations:**"));
    assert.ok(result.includes("- [ ] ")); // checkbox format
  });

  it("includes regulatory implications for each role", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("**Regulatory Implications if Unavailable:**"));
  });

  // ── DPO cross-training specifics ────────────────────────────────────────
  it("includes DPO-specific cross-training recommendations", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("GDPR Articles 12-23"));
    assert.ok(result.includes("runbook for DSAR handling"));
    assert.ok(result.includes("quarterly knowledge-sharing"));
  });

  // ── Incident Response GDPR 72-hour reference ───────────────────────────
  it("includes GDPR 72-hour notification for incident response by default", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("72 hours"));
    assert.ok(result.includes("GDPR Art. 33"));
  });

  // ── Bus Factor Analysis ─────────────────────────────────────────────────
  it("includes Bus Factor Analysis table", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("## Bus Factor Analysis"));
    assert.ok(result.includes("bus factor"));
    assert.ok(result.includes("| DSAR Handling | 1 | 3 |"));
    assert.ok(result.includes("| Breach Notification | 1 | 3 |"));
    assert.ok(result.includes("| Vendor DPA Management | 1 | 2 |"));
    assert.ok(result.includes("| Privacy Policy Updates | 1 | 2 |"));
  });

  it("includes AI Compliance in bus factor when AI detected", () => {
    const scan = makeScan({ services: [makeService("openai", "ai")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("| AI Compliance | 1 | 2 |"));
  });

  it("omits AI Compliance from bus factor without AI", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(!result.includes("AI Compliance"));
  });

  it("includes PCI DSS in bus factor when payment detected", () => {
    const scan = makeScan({ services: [makeService("stripe", "payment")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("| PCI DSS Compliance | 1 | 2 |"));
  });

  it("omits PCI DSS from bus factor without payment", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(!result.includes("PCI DSS Compliance"));
  });

  // ── 90-Day Action Plan ──────────────────────────────────────────────────
  it("includes 90-Day Action Plan with three months", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("## 90-Day Action Plan"));
    assert.ok(result.includes("### Month 1: Assign and Document"));
    assert.ok(result.includes("### Month 2: Cross-Train"));
    assert.ok(result.includes("### Month 3: Test and Validate"));
  });

  it("includes specific action items in Month 1", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Assign all unassigned compliance roles"));
    assert.ok(result.includes("Assign backup for every critical role"));
    assert.ok(result.includes("shared credential vault"));
  });

  it("includes simulation exercises in Month 3", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("Simulate DPO unavailability"));
    assert.ok(result.includes("Simulate security lead unavailability"));
    assert.ok(result.includes("quarterly recommended"));
  });

  // ── Disclaimer ──────────────────────────────────────────────────────────
  it("includes disclaimer about automated analysis", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("automated code analysis"));
    assert.ok(result.includes("Review with HR and leadership"));
  });

  // ── Comprehensive test ──────────────────────────────────────────────────
  it("handles all conditional sections together", () => {
    const scan = makeScan({
      services: [
        makeService("next-auth", "auth"),
        makeService("stripe", "payment"),
        makeService("posthog", "analytics"),
        makeService("openai", "ai"),
        makeService("sendgrid", "email"),
      ],
    });
    const result = generateKeyPersonRiskAssessment(scan, {
      companyName: "FullStack Inc",
      contactEmail: "hello@fullstack.io",
      dpoName: "Alice DPO",
      dpoEmail: "alice@fullstack.io",
      securityEmail: "sec@fullstack.io",
    })!;

    // All conditional roles present
    assert.ok(result.includes("Privacy Champion / Consent Manager"));
    assert.ok(result.includes("AI Governance Lead"));
    assert.ok(result.includes("Vendor Management Lead"));

    // Context values used
    assert.ok(result.includes("FullStack Inc"));
    assert.ok(result.includes("Alice DPO"));
    assert.ok(result.includes("alice@fullstack.io"));
    assert.ok(result.includes("sec@fullstack.io"));

    // Bus factor includes AI and PCI
    assert.ok(result.includes("AI Compliance"));
    assert.ok(result.includes("PCI DSS Compliance"));
  });

  // ── SPOF marking ────────────────────────────────────────────────────────
  it("marks core roles as single points of failure", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    // DPO, Security Lead, Incident Response Lead are all SPOF
    assert.ok(result.includes("**Single Point of Failure:** Yes"));
  });

  it("marks Compliance Training Coordinator as not SPOF", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    assert.ok(result.includes("**Single Point of Failure:** No"));
  });

  // ── Risk level icons ────────────────────────────────────────────────────
  it("uses risk level color icons in matrix", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    // Critical roles get red circle
    assert.ok(result.includes("\u{1F534} Critical"));
    // Medium roles get yellow circle
    assert.ok(result.includes("\u{1F7E1} Medium"));
  });

  // ── Role count in executive summary ─────────────────────────────────────
  it("counts roles correctly in executive summary — basic (4 roles)", () => {
    const scan = makeScan({ services: [makeService("next-auth", "auth")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    // DPO + Security Lead + Incident Response Lead + Compliance Training Coordinator = 4
    assert.ok(result.includes("| Key Compliance Roles | **4** |"));
  });

  it("counts roles correctly with analytics (5 roles)", () => {
    const scan = makeScan({ services: [makeService("posthog", "analytics")] });
    const result = generateKeyPersonRiskAssessment(scan)!;
    // 4 base + Privacy Champion = 5
    assert.ok(result.includes("| Key Compliance Roles | **5** |"));
  });

  it("counts roles correctly with AI + 3 services (7 roles)", () => {
    const scan = makeScan({
      services: [
        makeService("openai", "ai"),
        makeService("stripe", "payment"),
        makeService("next-auth", "auth"),
      ],
    });
    const result = generateKeyPersonRiskAssessment(scan)!;
    // 4 base + AI Governance Lead + Vendor Management Lead = 6
    assert.ok(result.includes("| Key Compliance Roles | **6** |"));
  });
});
